load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "tui",
    srcs = ["tui.cpp"],
    hdrs = ["tui.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//dom",
        "@ftxui",
    ],
)
