#!/usr/bin/env bash

grep --recursive --no-filename --only-matching --exclude-dir="*corpus" --exclude-dir=.github --exclude-dir="bazel-*" --exclude-dir=.cache --exclude-dir=external --exclude=MODULE.bazel --exclude=*test.cpp --exclude=ci.yaml --exclude="*.bazel.lock" 'https://[^)(}{",# ]*' | grep -v '^https://$' | sort | uniq | xargs wget --spider --no-verbose
