#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2024-2026 Robin Lindén <dev@robinlinden.eu>
#
# SPDX-License-Identifier: BSD-2-Clause

# Run all fuzz tests under a given pattern.
#
# If set, FUZZ_TAG can be used to filter fuzz tests by tag. If FUZZ_TAG starts
# with a dash, it will exclude tests with that tag.
#
# Example usage:
# ./bzl/run_fuzz_tests wasm/... --config libfuzzer -c dbg -- --timeout_secs=3

set -euo pipefail

PATTERN="$1"
shift

BASE_QUERY="filter(.*_fuzz_test_run\$, $PATTERN)"
QUERY="$BASE_QUERY"

if [[ -n "${FUZZ_TAG:-}" ]]; then
  if [[ "$FUZZ_TAG" == -* ]]; then
    TAG="${FUZZ_TAG#-}"
    QUERY="$BASE_QUERY except attr(tags, \"$TAG\", $BASE_QUERY)"
  else
    QUERY="attr(tags, \"$FUZZ_TAG\", $BASE_QUERY)"
  fi
fi

TARGETS=$(bazel query "$QUERY")

for tgt in ${TARGETS}; do
  bazel run "$tgt" "$@"
done
