#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2022 Robin Lindén <dev@robinlinden.eu>
#
# SPDX-License-Identifier: BSD-2-Clause

set -eu

readonly TEST_BINARY="$1"

shift 1

set +e
echo "Running test ${TEST_BINARY}" >&2
"${TEST_BINARY}" "$@"
RESULT="$?"
set -e

if [ "${RESULT}" -eq 0 ]; then
  echo "Test succeeded when it should have exploded" >&2
  exit 1
fi
